kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentName }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app:  {{ .Values.deploymentName }}
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      containers:
      - name: {{ .Values.deploymentName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: DEPLOYMENT_NAME
          value: {{ .Values.deploymentName }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      priorityClassName: {{ .Values.priorityClassName }}
