apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  IMAGES: "{{ .Values.configMap.images }}"
  DAEMONSET_NAME: "{{ .Values.deploymentName }}"
  DAEMONSET_ANNOTATIONS: {{ if kindIs "string" .Values.configMap.daemonsetAnnotations }}{{ .Values.configMap.daemonsetAnnotations | quote }}{{ else }}{{ .Values.configMap.daemonsetAnnotations | toJson | quote }}{{ end }}
  CACHING_INTERVAL_HOURS: "{{ .Values.configMap.cachingIntervalHours }}"
  NAMESPACE: "{{ .Release.Namespace }}"
  CACHING_MEMORY_REQUEST: "{{ .Values.configMap.cachingMemoryRequest }}"
  CACHING_MEMORY_LIMIT: "{{ .Values.configMap.cachingMemoryLimit }}"
  CACHING_CPU_REQUEST: "{{ .Values.configMap.cachingCpuRequest }}"
  CACHING_CPU_LIMIT: "{{ .Values.configMap.cachingCpuLimit }}"
  NODE_SELECTOR: {{ if kindIs "string" .Values.configMap.nodeSelector }}{{ .Values.configMap.nodeSelector | quote }}{{ else }}{{ .Values.configMap.nodeSelector | toJson | quote }}{{ end }}
  IMAGE_PULL_SECRETS: "{{ .Values.configMap.imagePullSecrets }}"
  AFFINITY: {{ if kindIs "string" .Values.configMap.affinity }}{{ .Values.configMap.affinity | quote }}{{ else }}{{ .Values.configMap.affinity | toJson | quote }}{{ end }}
  TOLERATIONS: {{ if kindIs "string" .Values.configMap.tolerations }}{{ .Values.configMap.tolerations | quote }}{{ else }}{{ .Values.configMap.tolerations | toJson | quote }}{{ end }}
  KIP_IMAGE: "{{ .Values.configMap.kipImage }}"
