kind: Template
apiVersion: v1
metadata:
  labels:
    app: kubernetes-image-puller
  name: kubernetes-image-puller
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    labels:
      app: kubernetes-image-puller
    name: ${DEPLOYMENT_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: kubernetes-image-puller
    strategy:
      type: "Recreate"
    template:
      metadata:
        labels:
          app: kubernetes-image-puller
      spec:
        containers:
        - name: kubernetes-image-puller
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          env:
          - name: DEPLOYMENT_NAME
            value: ${DEPLOYMENT_NAME}
          envFrom:
          - configMapRef:
              name: k8s-image-puller
        serviceAccountName: ${SERVICEACCOUNT_NAME}
parameters:
- name: DEPLOYMENT_NAME
  value: kubernetes-image-puller
- name: SERVICEACCOUNT_NAME
  value: k8s-image-puller
- name: IMAGE
  value: quay.io/eclipse/kubernetes-image-puller
- name: IMAGE_TAG
  value: next
