# Add Web IDE link on PRs
name: web-ide

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  add-link:
    runs-on: ubuntu-22.04
    steps:
      - name: Web IDE Pull Request Check
        id: try-in-web-ide
        uses: redhat-actions/try-in-web-ide@5cd0cae0eb96c2fb1673268173a821e35931b825 # v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
